parameters:
#    rosesareblue_jenkins.example.class: Rosesareblue\JenkinsBundle\Example

services:
#    rosesareblue_jenkins.example:
#        class: %rosesareblue_jenkins.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
