## YAML Template.
---
Rosesareblue\JenkinsBundle\Forms\BuildForm:
    properties:
        buildName:
          - NotBlank: ~
        refresh:
          - NotBlank: ~
          - Type: integer
        buildUrl:
          - Url: ~